import { useEffect, useState } from "react";

type Route = "dashboard" | "grammar" | "translation" | "word-lookup" | "word-review" | "practice" | "ask" | "handbook" | "coach";
const items: Array<[Route, string]> = [["grammar", "语法检查"], ["translation", "翻译"], ["word-lookup", "单词查询"], ["word-review", "单词 Review"], ["practice", "Practice"], ["ask", "Ask 对话"], ["handbook", "Handbook"], ["coach", "Coach"]];

async function requestJson<T>(url: string, init?: RequestInit): Promise<T> {
  const res = await fetch(url, { headers: { "Content-Type": "application/json" }, ...init });
  const payload = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error(payload.error?.message || payload.error || `HTTP ${res.status}`);
  return payload;
}

function Dashboard() {
  const [data, setData] = useState<any>(); const [error, setError] = useState("");
  useEffect(() => { requestJson("/dashboard").then(setData).catch((e) => setError(e.message)); }, []);
  if (error) return <State title="总览暂时不可用" detail={error} />;
  if (!data) return <State title="正在读取学习状态…" />;
  const focus = data.coach?.focus;
  return <><Heading eyebrow="OVERVIEW" title={<>今天，继续把表达<br /><em>变成自己的。</em></>} detail="你的学习证据正在形成。先完成一次短复测，再决定下一步。" /><section className="focus"><div><span className="eyebrow">CURRENT FOCUS</span><h2>{focus?.error_type || "从真实表达开始"}</h2><p>{focus ? `最近记录 ${focus.hits} 次，适合安排一次延迟复测。` : "还没有足够的稳定模式，先提交一句真实英文。"}</p><a className="primary" href="#grammar">开始表达 →</a></div><div className="orbit"><strong>{data.stats?.totalInputs || 0}</strong><span>ENTRIES</span></div></section><div className="columns"><Panel title="最近的表达">{(data.recentActivity || []).slice(0, 5).map((item: any) => <div className="activity" key={item.entryId}><small>{item.timestamp}</small><div><strong>{item.userInput}</strong><p>{item.correction || "已记录"}</p></div></div>)}{!data.recentActivity?.length && <State title="还没有 Review 记录" />}</Panel><Panel title="学习节奏"><div className="stat">{data.stats?.totalInputs || 0}<small> review entries</small></div><p>今日 {data.today?.inputs_today || 0} 条 · Vocabulary due {data.stats?.dueCounts?.vocab || 0}</p></Panel></div></>;
}

function Grammar() { const [text, setText] = useState(""); const [result, setResult] = useState<any>(); const [busy, setBusy] = useState(false); async function submit() { if (!text.trim()) return; setBusy(true); try { setResult(await requestJson("/grammar", { method: "POST", body: JSON.stringify({ text }) })); } catch (e: any) { setResult({ error: e.message }); } finally { setBusy(false); } } return <><Heading eyebrow="GRAMMAR CHECK" title="把一句话交给 IGT" detail="保留 Correction、Why、More natural 和 Remember 四层结果。" /><Panel title="你的英文表达"><textarea value={text} onChange={(e) => setText(e.target.value)} placeholder="例如：I suggested him to join the call." /><button className="primary" onClick={submit} disabled={busy}>{busy ? "检查中…" : "检查这句话 →"}</button></Panel>{result && <Panel title="检查结果"><pre>{JSON.stringify(result, null, 2)}</pre></Panel>}</>; }
function Translation() { const [text, setText] = useState(""); const [direction, setDirection] = useState("zh2en"); const [result, setResult] = useState<any>(); const [busy, setBusy] = useState(false); async function submit() { if (!text.trim()) return; setBusy(true); try { setResult(await requestJson("/translation", { method: "POST", body: JSON.stringify({ text, direction }) })); } catch (e: any) { setResult({ error: e.message }); } finally { setBusy(false); } } return <><Heading eyebrow="TRANSLATION" title="把意思说得自然" detail="翻译是独立的语言工具，不混入 Grammar 诊断。" /><Panel title="翻译输入"><div className="switches"><button className={direction === "zh2en" ? "selected" : ""} onClick={() => setDirection("zh2en")}>中 → 英</button><button className={direction === "en2zh" ? "selected" : ""} onClick={() => setDirection("en2zh")}>英 → 中</button></div><textarea value={text} onChange={(e) => setText(e.target.value)} placeholder="输入要翻译的句子…" /><button className="primary" onClick={submit} disabled={busy}>{busy ? "翻译中…" : "开始翻译 →"}</button></Panel>{result && <Panel title="翻译结果"><pre>{JSON.stringify(result, null, 2)}</pre></Panel>}</>; }
function Ask() { const [question, setQuestion] = useState(""); const [turns, setTurns] = useState<any[]>([]); const [busy, setBusy] = useState(false); const [saved, setSaved] = useState(""); async function send() { if (!question.trim()) return; const current = question.trim(); setQuestion(""); setBusy(true); try { const result = await requestJson<any>("/ask", { method: "POST", body: JSON.stringify({ question: current }) }); setTurns((old) => [...old, { question: current, answer: result.data?.answer || result.data }]); } catch (e: any) { setTurns((old) => [...old, { question: current, answer: `请求失败：${e.message}` }]); } finally { setBusy(false); } } async function save() { setSaved(""); try { const result = await requestJson<any>("/ask/save", { method: "POST", body: "{}" }); setSaved(result.saved ? "已保存到 Ask Markdown" : "当前没有可保存的咨询"); } catch (e: any) { setSaved(`保存失败：${e.message}`); } } return <><Heading eyebrow="ASK" title="把一个问题问到底" detail="当前线程保存在页面状态中，保存时写入 Ask Markdown。" /><Panel title="当前咨询">{turns.map((turn, index) => <div className="ask-turn" key={`${turn.question}-${index}`}><strong>{turn.question}</strong><p>{turn.answer}</p></div>)}{!turns.length && <State title="还没有问题" detail="从一个具体的语言问题开始。" />}<textarea value={question} onChange={(e) => setQuestion(e.target.value)} placeholder="继续追问…" /><button className="primary" onClick={send} disabled={busy}>{busy ? "思考中…" : "发送 →"}</button><button className="secondary" onClick={save}>保存到 Ask Markdown</button>{saved && <p className="status">{saved}</p>}</Panel></>; }
function WordReview() { const [cards, setCards] = useState<any[]>([]); const [index, setIndex] = useState(0); const [revealed, setRevealed] = useState(false); const [error, setError] = useState(""); useEffect(() => { requestJson<any>("/review/due?limit=20&type=vocab").then((data) => setCards(data.cards || [])).catch((e) => setError(e.message)); }, []); async function grade(rating: string) { const card = cards[index]; if (!card) return; try { await requestJson("/review/grade", { method: "POST", body: JSON.stringify({ card_id: card.id, correct: rating !== "again" }) }); setIndex((n) => n + 1); setRevealed(false); } catch (e: any) { setError(e.message); } } const card = cards[index]; return <><Heading eyebrow="VOCABULARY · SRS ONLY" title="词汇复习" detail="词汇内容来自 Markdown；这里只管理可重建的复习进度。" />{error && <State title="复习失败" detail={error} />}{!error && !card && <Panel title="今日状态"><State title={cards.length ? "今日复习完成" : "没有到期卡片"} detail={cards.length ? `完成 ${cards.length} 张词汇卡。` : "稍后再来，或先从词汇 Markdown 添加内容。"} /></Panel>}{card && <Panel title={`今日第 ${index + 1} / ${cards.length} 张`}><span className="eyebrow">{card.pos || "vocabulary"}</span><h2>{card.word || card.prompt}</h2><p>{revealed ? (card.answer || card.zh || card.meaning) : "先回忆，再显示提示"}</p><button className="primary" onClick={() => setRevealed(true)} disabled={revealed}>{revealed ? "已显示提示" : "显示记忆提示"}</button>{revealed && <div className="review-actions"><button onClick={() => grade("again")}>Again</button><button onClick={() => grade("hard")}>Hard</button><button onClick={() => grade("good")}>Good</button><button onClick={() => grade("easy")}>Easy</button></div>}</Panel>}</>; }
function Coach() { const [data, setData] = useState<any>(); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); async function load(refresh = false) { setBusy(true); setError(""); try { setData(await requestJson("/coach" + (refresh ? "/analyze" : "?windowDays=30"), refresh ? { method: "POST", body: "{}" } : undefined)); } catch (e: any) { setError(e.message); } finally { setBusy(false); } } useEffect(() => { load(); }, []); return <><Heading eyebrow="COACH · EVIDENCE" title="你的下一轮学习计划" detail="这里只呈现资产直接支持的观察，不把一次正确答案叫作掌握。" /><button className="secondary" onClick={() => load(true)} disabled={busy}>{busy ? "分析中…" : "重新分析资产"}</button>{error && <State title="Coach 暂时不可用" detail={error} />}{!data && !error && <State title="正在分析学习证据…" />}{data && <><Panel title="样本"><p>{data.sample?.totalInputs || 0} 条输入 · {data.sample?.totalDiagnoses || 0} 条诊断 · 窗口 {data.windowDays} 天</p></Panel>{(data.priorities || []).map((item: any) => <Panel key={item.errorType} title={item.errorType}><p>{item.mechanism?.statement}</p>{item.prescription?.slice(0, 2).map((phase: any) => <div className="activity" key={phase.phase}><strong>{phase.name}</strong><p>{phase.task}<br />检查：{phase.check}</p></div>)}</Panel>)}<Panel title="证据边界">{(data.limitations || []).map((item: string) => <p key={item}>· {item}</p>)}</Panel></>}</>; }
function WordLookup() { const [query, setQuery] = useState(""); const [entry, setEntry] = useState<any>(); const [status, setStatus] = useState(""); const [busy, setBusy] = useState(false); async function lookup() { if (!query.trim()) return; setBusy(true); setStatus(""); try { const result = await requestJson<any>(`/word/lookup?q=${encodeURIComponent(query.trim())}`); setEntry(result.data); } catch (e: any) { setStatus(e.message); } finally { setBusy(false); } } async function add() { try { const result = await requestJson<any>("/word/add", { method: "POST", body: JSON.stringify({ entry }) }); setStatus(result.persistence?.saved ? "已保存到 Vocabulary Markdown" : "这个词已经存在"); } catch (e: any) { setStatus(e.message); } } return <><Heading eyebrow="WORD LOOKUP" title="查一个词，也把它留下" detail="查询结果可以保存到 Vocabulary Markdown，并进入词汇复习。" /><Panel title="查询单词或短语"><div className="lookup-row"><input value={query} onChange={(e) => setQuery(e.target.value)} onKeyDown={(e) => e.key === "Enter" && lookup()} placeholder="例如：consolidate" /><button className="primary" onClick={lookup} disabled={busy}>{busy ? "查询中…" : "查询 →"}</button></div></Panel>{entry && <Panel title={entry.word}><p><strong>{entry.pos}</strong></p><p>{entry.meaning}</p><p>{entry.zh}</p><p>{entry.example}</p><button className="primary" onClick={add}>加入词汇资产</button></Panel>}{status && <p className="status">{status}</p>}</>; }
function Practice() { const [questions, setQuestions] = useState<any[]>([]); const [index, setIndex] = useState(0); const [answer, setAnswer] = useState(""); const [evaluation, setEvaluation] = useState<any>(); const [busy, setBusy] = useState(false); async function generate() { setBusy(true); setEvaluation(undefined); try { const result = await requestJson<any>("/practice/generate", { method: "POST", body: JSON.stringify({ mode: "sentence", count: 3 }) }); setQuestions(result.data?.questions || []); setIndex(0); } catch (e: any) { setEvaluation({ error: e.message }); } finally { setBusy(false); } } async function evaluate() { const question = questions[index]; if (!question || !answer.trim()) return; setBusy(true); try { const result = await requestJson<any>("/practice/evaluate", { method: "POST", body: JSON.stringify({ question, answer }) }); setEvaluation(result.data); } catch (e: any) { setEvaluation({ error: e.message }); } finally { setBusy(false); } } const question = questions[index]; return <><Heading eyebrow="PRACTICE" title="在新语境里自己写出来" detail="Practice 记录独立产出，不直接成为 Coach 的语法证据。" />{!question && <Panel title="开始一次练习"><State title="准备好后生成 3 道题" /><button className="primary" onClick={generate} disabled={busy}>{busy ? "生成中…" : "生成练习 →"}</button></Panel>}{question && <Panel title={`第 ${index + 1} / ${questions.length} 题`}><h2>{question.prompt_zh}</h2><p>{question.focus || "写出完整英文句子。"}</p><textarea value={answer} onChange={(e) => setAnswer(e.target.value)} placeholder="写出你的英文答案…" /><button className="primary" onClick={evaluate} disabled={busy}>提交评价 →</button>{evaluation && <div className="evaluation"><pre>{JSON.stringify(evaluation, null, 2)}</pre><button className="secondary" onClick={() => { setIndex((n) => n + 1); setAnswer(""); setEvaluation(undefined); }}>下一题</button></div>}</Panel>}</>; }
function Handbook() { const [data, setData] = useState<any>(); const [selected, setSelected] = useState(""); const [error, setError] = useState(""); useEffect(() => { requestJson<any>("/handbook?days=90").then((value) => { setData(value); setSelected(value.selected || ""); }).catch((e) => setError(e.message)); }, []); async function choose(value: string) { setSelected(value); try { setData(await requestJson(`/handbook?days=90&errorType=${encodeURIComponent(value)}`)); } catch (e: any) { setError(e.message); } } if (error) return <State title="Handbook 暂时不可用" detail={error} />; if (!data) return <State title="正在读取 Handbook…" />; return <><Heading eyebrow="HANDBOOK · REFERENCE" title="从真实错误找到解释" detail="Handbook 提供参考资料，不会自动变成你的错误证据。" /><div className="handbook-list">{(data.frequencies || []).map((item: any) => <button className={selected === item.error_type ? "selected" : ""} key={item.error_type} onClick={() => choose(item.error_type)}>{item.error_type}<span>{item.count}</span></button>)}</div><Panel title={selected || "暂无错误类型"}>{data.examples?.length ? data.examples.map((item: any, index: number) => <div className="activity" key={index}><strong>{item.original_text}</strong><p>{item.correction}<br />{item.explanation}</p></div>) : <State title="还没有可展示的实例" detail="先提交真实表达，Handbook 会按记录提供参考。" />}</Panel></>; }
function Placeholder({ title }: { title: string }) { return <><Heading eyebrow="WORKSPACE" title={title} detail="页面骨架已就绪，正在接入对应的真实工作流。" /><Panel title="Local Web 工作区"><State title="Application API 已准备" detail="下一步将接入该工作区的页面交互和状态流。" /></Panel></>; }
function Heading({ eyebrow, title, detail }: { eyebrow: string; title: React.ReactNode; detail: string }) { return <div className="heading"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{detail}</p></div>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="panel"><span className="eyebrow">IGT</span><h2>{title}</h2>{children}</section>; }
function State({ title, detail }: { title: string; detail?: string }) { return <div className="state"><strong>{title}</strong>{detail && <p>{detail}</p>}</div>; }

export function App() { const [route, setRoute] = useState<Route>((location.hash.slice(1) || "dashboard") as Route); useEffect(() => { const onHash = () => setRoute((location.hash.slice(1) || "dashboard") as Route); addEventListener("hashchange", onHash); return () => removeEventListener("hashchange", onHash); }, []); const title = items.find(([key]) => key === route)?.[1] || "总览"; const page = route === "dashboard" ? <Dashboard /> : route === "grammar" ? <Grammar /> : route === "translation" ? <Translation /> : route === "ask" ? <Ask /> : route === "word-review" ? <WordReview /> : route === "coach" ? <Coach /> : route === "word-lookup" ? <WordLookup /> : route === "practice" ? <Practice /> : route === "handbook" ? <Handbook /> : <Placeholder title={title} />; return <div className="shell"><aside><a className="brand" href="#dashboard">IGT</a><span className="side-label">学习工作台</span><button className={`nav ${route === "dashboard" ? "active" : ""}`} onClick={() => { location.hash = "dashboard"; }}>总览</button>{items.map(([key, label]) => <button className={`nav ${route === key ? "active" : ""}`} key={key} onClick={() => { location.hash = key; }}>{label}</button>)}</aside><main><header><span>IGT / {title}</span><span className="runtime">Local · Markdown + SQLite</span></header>{page}</main></div>; }
