import focuses from "./language-focuses.json" with { type: "json" };

// Authored Chinese prompts for the challenge band. Every item combines at least two
// grammar dimensions in one realistic sentence and keeps the focus as the hard part.
// Fields: focus ~ prompt ~ reference ~ meaning cue ~ construction cue ~ open pattern ~ category ~ purpose ~ relationship.
const AUTHORED = String.raw`
G01.1~尽管三位候选人都通过了笔试，评审委员会却一直没有决定最后录用谁。~Although all three candidates passed the written test, the review committee still has not decided whom to hire in the end.~一句里有两套主语，动词必须各自跟随。~all three candidates 是复数用 passed；the review committee 是单数，尚未完成的否定用 has not decided。~Although [复数主语] + V-ed, [单数主语] + has not (yet) + V-ed + whom to V + [时间]~fWRo~d~x
G01.1~厨房、书房和阳台的灯全亮着，唯独客厅那一盏坏了半年，至今没人修过。~The lights in the kitchen, the study and the balcony are all on, except for the one in the living room, which has been broken for six months and which nobody has ever fixed.~主语被长长的地点修饰语隔开，仍要与最前面的中心词一致。~主语中心是 lights（复数）用 are；which 从句里 broken 保留过去分词，nobody has fixed 用完成时。~[地点A], [地点B] and [地点C] + are all + [状态], except for [另一地点] + one, which + has been + V-ed + for + [时长]~nECo~d~x
G01.2~上个月我们只处理了三十七封来信，却把整整两周的时间都花在逐字核对引文上。~Last month we handled only thirty-seven letters, yet we spent a full two weeks checking every citation word for word.~同一段时间里，处理的对象和花掉的精力完全不同。~handled 是 handle 的过去式；word for word 是固定副词短语，位置在动词之后。~[过去时间] + [主语] + V-ed only + [数量及对象], yet + [主语] + spent + [时长] on + [名词短语]~fWRn~e~x
G01.2~负责采购的同事既没有确认供应商的报价，也没有把样品寄回来，项目因此一直卡在评审环节。~The colleague in charge of procurement neither confirmed the supplier's quote nor sent the samples back, which is why the project has been stuck at the review stage.~两件未完成的事都用过去时，之后的结果仍在持续。~neither...nor 后接两个过去式并保持结构一致；which is why 引出结果。~[主语] + neither + V-ed + [对象] + nor + V-ed + [对象], which is why + [现在完成时从句]~fWRd~e~r
G01.3~这套系统在高峰时段确实稳定，可一旦记录数超过三千万条，就很难说它还稳不稳。~The system is stable at peak times, but once the number of records exceeds thirty million, it is hard to say whether it still stays stable.~前半句用形容词描述状态，后半句把状态本身变成疑问。~is stable 是系表结构；hard to say whether 之后用陈述语序。~[主语] + is + [形容词], but once + [条件从句], it is hard to say whether + [陈述]~fWRo~e~c
G01.3~这位候选人的技术背景确实扎实，只是过去三年里他换过的岗位有点多。~The candidate's technical background is indeed solid; the only thing that counts against him is that he has changed jobs rather often in the past three years.~前半评价能力，后半把评价落到具体一件事上。~is solid 是系表；the only thing that...is that 承载让步信息，has changed 用现在完成时。~[主语] + 's + [名词] + is + [形容词]; the only thing that [主语] + V-ed is that + [完成时从句]~fWRo~v~x
G01.4~财务部昨天把完整的审计材料寄给了我们，同时又提醒我们不要转发给外部的顾问。~The finance department sent us the complete audit files yesterday, and at the same time told us not to forward them to outside consultants.~同一批材料既被寄出，又附带一条使用限制。~send sb sth 用双宾语；not to do 是不定式的否定形式。~[机构] + V-ed [接收者] + [文件] + [过去时间], and at the same time + V-ed [人] + not to V + [对象]~fWEd~i~a
G01.4~只要董事会能在下周五之前给我们一份明确的优先级清单，我们就能把开发排期提前两周锁定下来。~As long as the board can give us a clear list of priorities before next Friday, we will be able to lock in the development schedule two weeks earlier.~条件是拿到清单，拿到之后带来的是提前两周。~as long as 从句用现在时；will be able to 表未来能力；lock in 是多词动词。~As long as + [主语] + can V + [条件与期限], [主语] + will be able to + lock in + [对象] + [提前幅度]~fWRn~f~c
G01.5~连续多日通宵赶稿把整个团队都熬垮了，这也是后来进度一再延后的直接原因。~Working through the night for days on end wore the whole team out, which is the direct reason for the repeated delays in the schedule.~一个动作造成了某种状态，状态又解释了后面的结果。~wear sb out 用宾语补语表状态；which is the direct reason for 引出原因。~[名词化主语] + V-ed + [宾语] + [状态形容词], which is the direct reason for + [名词化事件]~fWRo~r~r
G01.5~请务必把最终版本标记为只读，并在归档之前把其中的敏感字段全部删掉。~Please be sure to mark the final version as read-only and delete all the sensitive fields in it before archiving.~两步都要做到，顺序和对象都不同。~mark A as B 中 B 是形容词补语；be sure to do 保留不定式。~Please be sure to + mark + [对象] + as + [状态] + and + V + [对象] + before + [名词化动作]~nWNd~r~t
G01.6~会上其实一直有两种不同的声音，只是从来没有人愿意先把分歧摆到桌面上来。~There have actually been two different voices in the meeting; nobody has ever been willing to put the disagreement on the table first.~引出的是一种持续存在的现象，而不是某个具体的人。~there have been 表从过去持续到现在；put...on the table 是可分短语。~There have been + [复数名词] + [修饰语]; nobody has been willing to + [动作短语]~fWMn~i~x
G01.6~按照新流程，只有在完成全部合规检查之后，系统里才会出现可用的临时账号。~Under the new procedure, a usable temporary account will not appear in the system until all the compliance checks have been completed.~引出的对象要等到条件成立之后才出现。~存在句的否定可改写为 not appear；until 之后用现在完成时表已完成。~Under + [依据], [单数名词] + will not appear + [地点] + until + [主语] + have been + V-ed~fWNd~i~t
G01.7~直到第三季度我们才意识到，真正卡住项目的并不是技术，而是没有人敢在期限之前说不。~It was not until the third quarter that we realised that what was really holding the project up was not the technology but the fact that nobody dared to say no before a deadline.~强调的是一个时间点，被否定的内容放在从句里。~It was not until...that 结构；what 从句作表语时谓语用单数。~It was not until + [时间] + that + [主语] + realised that + what + was really V-ing + was not + [名词] + but + [the fact that + 从句]~fWRo~f~x
G01.7~值得商榷的是，把这次调整当成个人失误来处理，是否真的有助于解决问题。~It is debatable whether treating this adjustment as an individual mistake really helps solve the problem.~评价的对象是"这样做是否有用"这个动作。~It is debatable whether 后用陈述语序；treat A as B 中 as 引出身份。~It is debatable whether + [名词化动名词短语] + really helps to V + [对象]~fWRo~v~c
G02.1~请问这批样品在送检之前，是不是已经按照最新版的标准重新抽检过一轮？~Have these samples already been re-sampled against the latest standard before they were sent for testing?~问的是过去是否完成的动作，但现在仍在关心。~现在完成时被动语态用 have been + 过去分词；before 从句用过去时。~Have + [复数名词] + already been + V-ed against + [标准] + before + [主语] + were + V-ed?~fXEo~q~t
G02.1~你是不是也察觉到，季度数据里其实存在两处一直没人能解释清楚的口径差异？~Have you noticed as well that there are actually two definitional discrepancies in the quarterly figures that nobody has been able to explain?~察觉的是一个一直存在却没人解释的现象。~引导宾语从句用 that；existential 用 there are；解释不了用现在完成时的被动否定。~Have you noticed as well that + there are + [复数名词] + [修饰语] + that + nobody has been able to + [解释动作]~nWCo~q~e
G02.2~究竟是哪一项配置变更，导致三月份以后的报表全部对不上账？~Which configuration change was it that caused the reports after March to stop reconciling with the accounts?~要查的是一个具体的变更项，后果是持续的。~which 引导词后加 it 强调；stop doing 表动作停止。~Which + [变更项] + was it that + V-ed + [后果主语] + to [名词化动作]~fWRo~q~r
G02.2~如果供应商四十八小时内不能书面确认这一点，我们该拿什么证据去跟海关交涉？~If the supplier cannot confirm this in writing within forty-eight hours, what evidence can we use to negotiate with the customs office?~先假设一种情况，再问该做什么。~if 从句用现在时；疑问词后用陈述语序。~If + [主语] + cannot V + [期限], what + [名词] + can we use to + [目的动作]~fTXt~q~c
G02.3~究竟是谁在最后关头改掉了那句措辞，让整份声明的法律风险一下子降了下来？~Who was it who changed the wording at the last minute and brought the legal risk of the whole statement down at once?~要查的是执行者，动作带来了结果。~who 引导从句作主语，本身不加 do；bring A down 表降低。~Who was it who + V-ed + [对象] + at the last minute + and + V-ed + [风险] + down + at once?~fWRo~q~r
G02.3~哪些环节的延误，真正拖慢了整整一个交付窗口？~Which stages of the process actually slowed down the entire delivery window?~问的是一批环节，不是单个。~which 直接修饰 stages；动词用过去时，方式状语后置。~Which + [复数名词] + of + [范围] + actually + V-ed + [宾语]~nWRd~q~r
G02.6~这份材料你到底有没有在会前发给对方？~Have you actually sent this material to them before the meeting or not?~疑问落在现在之前是否完成的动作上。~助动词用 have 而不是 do；反意疑问用 or not。~Have + [主语] + actually + V-ed + [对象] + [时间] + or not?~cWCn~q~t
G02.6~你能不能确认一下，他在提交之前是不是真的把清单从头到尾核对了一遍？~Could you confirm whether he really went through the list from beginning to end before he submitted it?~请对方核实一个尚未确认的过去动作。~间接疑问用 whether；go through 表示逐项核对。~Could you confirm whether + [主语] + really + V-ed + [对象] + before + [过去时从句]~nWCo~q~t
G03.1~我父亲只要一有空就往阳台跑，住了三十年，阳台上的花盆却已经换过三轮了。~My father spends every spare moment on the balcony; even though he has lived here for thirty years, the pots on the balcony have been replaced three times over.~习惯动作与已经改变的结果同时出现。~spends...every spare moment 表习惯用现在时；have been replaced 表累计结果。~[主语] + V-s + [频率状语], even though + [现在完成时从句], [主语] + have been + V-ed + [次数]~cECf~i~x
G03.1~过去这些年我们每逢假期都回那个海边小镇，可这几年一次也没回去过。~For years we used to go back to the same seaside town every holiday, but in recent years we have not been back even once.~过去的习惯与近年的中断形成对比。~used to 表示已停止的旧习惯；have not been back 表至今未发生。~For + [时长] + [主语] + used to V + [频率], but + [主语] + have not been + [地点] + even once~nECo~i~x
G03.2~这个问题在会上一直悬而未决，因为谁都不愿意先承认方案本身可能有问题。~The question has hung unresolved throughout the meeting, because nobody is willing to admit first that the plan itself may be flawed.~一个未解决的状态持续存在，原因出在人的意愿。~has hung unresolved 是现在完成时；may be flawed 保留可能性。~[主语] + has + [过去分词] + [状态] + throughout + [时段], because + [主语] + is willing to + [否定动作]~fWRn~e~r
G03.2~我现在完全不怀疑这家供应商的专业能力，可他们的交付节奏确实让我们很难安排生产。~I don't doubt the supplier's professional competence at all at the moment, but their delivery rhythm really makes it hard for us to arrange production.~先完全肯定一个方面，再指出另一个方面的困难。~don't doubt 否定的是想法而非动作；make it hard for sb to do 保留不定式。~[主语] + don't doubt + [对象] + at all, but + [主语] + make it hard for [人] + to + [动作]~nXCo~e~x
G03.3~我们正在等财务那边把最终数字确认下来，而供应商已经在催第三批货的付款了。~We are waiting for the finance side to confirm the final figures, while the supplier is already pressing for payment for the third batch.~两件事在同一时段内同时进行。~wait for sb to do 用不定式；while 引导对比；pressing for 用进行时表当下。~[主语] + are + V-ing for + [人] + to + [动作], while + [主语] + is already + V-ing for + [对象]~fWRo~i~x
G03.3~昨天这个时候整栋楼都在为停电的事吵得不可开交，而我们连一句解释都没听到。~At this time yesterday the whole building was arguing about the power cut, and we didn't hear a single explanation.~明确的时间点落在一个正在进行的动作上。~背景动作用过去进行时；简短动作用一般过去时。~At + [过去时间点] + [主语] + was + V-ing + about + [事件], and + [主语] + didn't V + [对象]~cECf~i~x
G03.4~上个季度我们把预算砍掉了一成半，上线日期却反而提前了两周。~Last quarter we cut the budget by fifteen per cent, yet the launch date ended up two weeks earlier.~两件已完成的事产生了方向相反的结果。~cut 的过去式不变；end up 表最终结果。~[过去时间] + [主语] + V-ed + [对象] + by + [幅度], yet + [主语] + ended up + [结果]~fWRn~i~x
G03.4~三年前他一个人把整套测试流程从零搭起来，去年却连一次都没有维护过。~Three years ago he built the whole testing process from scratch on his own, but last year he did not maintain it even once.~早期的重大动作与后期的零维护并列。~build 的过去式是 built；带频率的否定用 did not + 动词原形。~[过去时间] + [主语] + V-ed + [对象] + from scratch, but + [过去时间] + [主语] + did not + V + [对象] + even once~fWRn~i~x
G03.9~团队本来打算在年底前把重构做完，可现在看来，要么拖到明年，要么就得牺牲一半的测试。~The team had intended to finish the refactoring before the end of the year, but as things stand now, they either delay it into next year or they sacrifice half of the tests.~过去的打算与眼前只能二选一的处境。~had intended 表过去已有的打算；either...or 两端保持谓语形式。~[主语] + had intended to V + [期限], but as things stand now, + [主语] + either + V + or + V + [代价]~fWRn~f~x
G03.9~一旦总部批复下来，我们立刻启动招聘；但在那之前，谁也不能对外承诺任何时间表。~As soon as headquarters gives approval, we will start recruiting immediately; but until then, nobody may promise any timetable externally.~未来有两种时序，一个紧跟条件，一个持续到条件之前。~as soon as 从句用现在时；will 表即时决定；until then 之前用 may not。~As soon as + [主语] + V-s, [主语] + will + [名词化动作] + immediately; but until then, nobody may not promise + [对象]~fWRd~i~t
G03.10~如果下一轮融资在年底前落不了地，团队里恐怕有一半人撑不到明年春天。~If the next funding round cannot be closed before the end of the year, half of the team may well not last until next spring.~条件不确定，结果也带着风险。~if 从句用现在时；may well 表有理由怀疑的可能。~If + [现在时条件], [主语] + may well not + [结果状态] + until + [时间]~fWRn~f~c
G03.10~如果后端迁移这周还完不成，我们多半只能把灰度范围再往后推两周。~If the backend migration is not completed this week, we will most probably have to push the scope of the roll-out back by another two weeks.~预测的是被迫调整之后的计划。~if 从句用现在时表未完成；have to 表被迫；by another 表增量。~If + [主语] + is not + V-ed + [期限], [主语] + will most probably have to + [调整动作] + by another + [增量]~fWRn~f~c
G04.1~没有一个人能在两天之内既把这套系统读完，又向董事会讲清它的全部风险。~Nobody can both finish reading this system in two days and explain all of its risks clearly to the board.~同一段时间里要完成两件能力要求都很高的事。~can 后接动词原形；both...and 并列两个原形不定式。~Nobody can both + V + [对象] + in + [时长] + and + V + [对象] + to + [对象]~fWRd~v~x
G04.1~三年前他还能连着熬三个通宵，如今连一个通宵都撑不下来。~Three years ago he could still work through three nights in a row; nowadays he cannot get through even a single one.~过去的能力和现在的不行形成对照。~could 表过去能力；cannot 之后直接接动词原形。~[过去时间] + [主语] + could still + V + [次数], nowadays + [主语] + cannot + V + even + [最小数量]~cECf~i~x
G04.2~出于合规考虑，未经书面批准，任何人都不得把这批数据导出到本地磁盘。~For compliance reasons, nobody may export this batch of data to a local disk without written approval.~这是许可问题，而且附加了一个前置条件。~may 表许可；without 后接名词表示缺失条件。~For + [理由], nobody may + V + [对象] + to + [地点] + without + [许可条件]~fWRd~r~c
G04.2~只要不影响生产环境，你可以在测试库里做任何实验，但请不要动共享的表结构。~Provided that it does not affect the production environment, you may do any experiment you like in the test database, but please do not touch the shared table structure.~许可有一个边界条件，还有一条明确禁止。~provided that 引导的条件从句用现在时；否定祈使句省略主语。~Provided that + [现在时条件], [主语] + may + V + [范围], but please do not + V + [对象]~nWNd~r~c
G04.5~未经客户书面授权，任何人不得截取、剪辑或以其他方式改动已经交付的访谈录音。~Without the client's written authorisation, nobody may cut, edit or in any other way alter the interview recordings that have already been delivered.~禁止的范围覆盖三种处理方式。~may not 表禁止；or in any other way 扩展禁止范围；that 从句修饰录音。~Without + [许可条件], nobody may not + V1, V2 or in any other way + V3 + [完成时分句修饰的录音]~fWRd~r~c
G04.5~红灯亮起之前不得关闭安全阀，值班记录也必须每两小时抄送一次值班主管。~The safety valve must not be closed before the warning light comes on, and the duty log must be copied to the duty supervisor every two hours.~两条要求一禁一务，还有一条时间限制。~must not 表禁止；every two hours 表重复间隔。~[设备] + must not be + V-ed before + [现在时条件], and [记录] + must be + V-ed to + [人] + every + [时长]~fWNd~r~t
G04.6~与其反复向上级解释需求，不如先把能交付的部分做出来，再用证据去争取剩下的资源。~Rather than explaining the requirements to your manager again and again, you would be better off building the deliverable part first and then using the evidence to secure the remaining resources.~建议包含"不要做什么"和"改做什么"两层。~Rather than 后接动名词；had better 后接动词原形。~Rather than + V-ing + [对象], [主语] + had better + V + [对象] + first + and then + [第二个动作]~nWCd~s~x
G04.6~越是到了压力最大的阶段，越要守住已经定下来的评审流程，否则返工的成本只会更高。~The more pressure the project is under, the more important it is to hold to the review process that has already been agreed; otherwise the cost of rework will only be higher.~建议的强度随条件变化，并带一条后果说明。~the more..., the more... 表比例递增；otherwise 引出反向结果。~The more + [条件], the more + important it is + to + [动作] +; otherwise + [代价] + will only be + 比较级~nWCa~s~c
G07.1~先把合同条款逐条对齐，再让法务确认，最后才轮到财务核对付款条件，这三步任何一步都不能省。~First align the contract clauses one by one, then have legal confirm them, and only after that let finance check the payment terms; none of the three steps can be skipped.~三个步骤按顺序发生，顺序本身是重点。~have sb do 与 let sb do 都用省略 to 的不定式；none of 后接复数名词。~First + [动作A], then + have [方] + do, and only after that + let [方] + do; none of + [复数名词] + can be + V-ed~fWRo~r~t
G07.1~他不但把方案改到没人看得懂，还顺手删掉了所有能追溯的修改记录。~He not only rewrote the proposal until nobody could follow it but also removed every record of the changes that could be traced.~两个越界行为并列，前一个还是累积过程。~not only...but also 连接两个谓语；until 引出结果。~[主语] + not only + V-ed until + [结果], but also + V-ed + [对象]~cWCd~v~x
G07.2~凡是经过审计确认的供应商，都必须在上线前完成一次独立的安全评估。~Any supplier that has passed the audit must complete an independent security assessment before going live.~先限定一个集合，再对集合中的每个成员提出要求。~that 引导的定语从句用现在完成时；before 后接动名词。~Any + [复数名词] + that has been + V-ed must + V + [对象] + before + [动名词]~fWNd~r~c
G07.2~这份报告里唯一还没有被复核过的数字，是第 47 页上的那个复购率。~The only figure in this report that has not been double-checked yet is the repurchase rate on page forty-seven.~用唯一性限定一个数字，再点明它是哪一个。~the only + 名词 + that 从句构成主语中心；is 表判断。~The only + [单数名词] + that has not been + V-ed + is + [具体说明] + on + [位置]~fWRo~i~e
G07.3~上一轮评审把范围扩到了移动端，而移动端恰恰是我们唯一没有自动化测试的环节。~The last review widened the scope to the mobile side, which happens to be the only part of the system where we have no automated tests at all.~一句话里给出扩围范围，再加一层补充说明。~which 在此指代整个前句；where 引导地点限定从句。~[主语] + V-ed + [对象], which happens to be + the only + [名词] + where + [现在时从句]~fWRo~i~x
G07.3~他们提出延期，理由是供应商还没签字，而所有人都清楚那不过是拖延的借口。~They asked for an extension on the grounds that the supplier had not signed yet, which everyone knows is nothing more than an excuse for delay.~转述理由之后再补一层判断。~on the grounds that 后接原因从句；which 引出附加评价。~[主语] + asked for + [延期] + on the grounds that + [原因从句], which everyone knows is + [评价]~fWRo~v~x
G07.5~客户一确认最终版本，我们就把排产计划锁定下来，此后任何改动都必须走变更流程。~As soon as the client confirms the final version, we lock the production schedule, and any change after that has to go through the change process.~有一个明确的触发时刻，之后还有长期约束。~as soon as 从句用现在时；after that 之后用现在完成时表遗留状态。~As soon as + [现在时条件], [主语] + V + [对象] + and any change after that has to + [名词化动作]~fWNn~i~t
G07.5~到下个迭代结束时，我希望能给出三个可以比较的方案，而不是一个只能事后解释的选择。~By the end of the next iteration, I hope to be able to offer three comparable options rather than one choice that can only be explained afterwards.~目标状态与要避免的状态形成对比。~by the end of 表期限；rather than 后接名词短语。~By + [期限], [主语] + hope to be able to + [提供] + [数量与定语], rather than + [要避免的名词短语]~fWRn~s~x
G07.8~他把改动一次性全推到了生产环境，结果那天下午几乎所有服务都超时了。~He pushed all the changes to the production environment in one go, with the result that almost every service timed out that afternoon.~一个动作直接导致一个可观察的结果。~with the result that 专门引出结果；push 的过去式不变。~[主语] + V-ed + [对象] + [方式], with the result that + [主语] + V-ed + [时间]~fWRo~i~s
G07.8~我们把测试环境调得和线上完全一致，结果真正的性能问题反而更早暴露了出来。~We tuned the test environment to match production exactly, and the real performance problems came out earlier instead.~做了预期中的事，却得到非预期的结果。~to match 是目的状语；instead 表出乎意料。~[主语] + V-ed + [对象] + to + [目的], and + [问题] + V-ed + [比较级] + instead~fWRo~i~x
G07.11~他在周报里写得轻描淡写，好像那次故障根本没有发生过一样。~In the weekly report he wrote it as though the outage had never happened at all.~文字的语气与事实形成反差。~as though 引导方式状语从句，内含过去完成时。~In + [书面材料] + [主语] + V-ed it + as though + [过去完成时从句]~fWRn~v~x
G07.11~他们把扩容脚本写得像是随时可以重来一遍，可脚本本身从来没有在真实负载下跑通过一次。~They wrote the scaling script as if it could be run again at any time, yet it has never once been tested under real load.~表面能力与实际验证情况不一致。~as if 后用过去式表与事实相反；yet 引出转折。~[主语] + V-ed + [对象] + as if + [过去时从句], yet it has never once been + V-ed + under + [条件]~fWRn~v~x
G08.1~我宁愿把整件事推翻重来，也不愿意在一个没人说得清前提的方案上继续加补丁。~I would rather start the whole thing over than keep adding patches to a plan whose premises nobody can explain.~在两个都不理想的选项之间取舍。~would rather 后接动词原形；whose 引出所属关系。~[主语] + would rather + V + [对象] + than + keep + V-ing + [对象] + whose + [名词]~cECf~v~x
G08.1~方向一旦错了，越早停下来承认，损失就越小。~The earlier you admit that the direction is wrong and stop, the smaller the loss will be.~两个变量同时变化，一早一晚对比结果。~the + 比较级..., the + 比较级... 构成比例句。~The + 比较级 + [主语] + [动作], the + 比较级 + [主语] + will be + [结果]~nWCa~s~m
G08.2~记得当天就把会议纪要发出去，别等到所有人都已经散了才想起来。~Remember to send the minutes out on the same day rather than waiting until everyone has already dispersed.~提醒的内容包含该做与不该拖。~remember to do 与 remember doing 意义不同；wait until 中用现在完成时。~Remember to + V + [对象] + [时间] + rather than + V-ing until + [完成时从句]~nWNd~s~t
G08.2~他一听说要提前上线就开始推卸责任，后来再也没人愿意听他说完。~The moment he heard that the launch would be brought forward, he started passing the buck, and after that nobody was willing to hear him out.~一个瞬间引发一个持续的后果。~the moment 引导的时间从句用过去时；hear sb out 是可分短语。~The moment + [过去时从句], [主语] + started + [动作] + and after that nobody was willing to + [短语]~fWRn~i~r
G09.3~这类问题过去三年被提过无数次，但至今没有一个部门真的把它当成自己的责任。~This kind of question has been raised countless times over the past three years, yet not one department has really taken it on as its own responsibility.~一件被反复提起却无人承担的事。~现在完成被动表反复发生；not one 作主语时后接单数。~[名词短语] + has been + V-ed + [次数与时段], yet not one + [单数名词] + has really + V-ed~fWRn~v~x
G09.3~数据、文档和访问权限这三样里，只有第一样是共享的，另外两样各归不同的人管。~Of data, documentation and access permissions, only the first is shared, and the other two are each owned by a different person.~三个并列项里只有一项符合条件。~of 提到集合在前；each 用于强调逐个分配。~Of + [A], [B] and [C], only the first + is + [状态], and the other two are each + V-ed by + [不同的人]~nWRo~i~x
G09.4~这些需求里没有一条能由现有团队在两周内完成，但我们仍然承诺了其中至少三条。~Not one of these requirements can be completed by the current team within two weeks, yet we have still committed to at least three of them.~全否定与部分承诺形成冲突。~not one of 后接复数名词但谓语用单数；at least three of them 指回名词。~Not one of + [复数名词] + can be + V-ed + [期限], yet + [主语] + have still committed to + [数量 + of them]~fWRn~v~x
G09.4~无论是法务还是业务，都不该在没有数据的情况下替对方拍板。~Neither legal nor the business side should make the call for the other without data.~两个部门都不该越界替对方决定。~neither...nor 连接两个主语时谓语就近；without 后接名词表示条件缺失。~Neither + [A] + nor + [B] + should + V + for + [另一方] + without + [条件]~fWRo~r~c
G09.5~把会上提到的每一个细节都落到文档上，听起来简单，做起来要花掉整整两天。~Turning every detail mentioned in the meeting into documented form sounds simple, but in practice it takes a full two days.~同一件事，听起来和做起来差别很大。~sounds simple 与 takes two days 分属不同主语；in practice 表实际。~[动名词短语] + sounds + [形容词], but in practice it takes + [时长]~cWCo~e~x
G09.5~大多数人以为风险在于技术，其实更大的风险在于没有人愿意为结果负责。~Most people assume that the risk lies in the technology, whereas the greater risk is that nobody is willing to take responsibility for the outcome.~一般看法与实际情况不同。~Most people 配复数；whereas 引出对比；the greater risk 表比较。~Most people assume that + [从句], whereas the + 比较级 + is that + [从句]~nECo~e~m
G09.6~这张流程图是财务和运营两个部门去年冬天共同画的，谁也没有真正拥有它。~This flowchart was drawn jointly by finance and operations last winter, and neither department really owns it.~两个人共同完成，但责任归属空缺。~过去被动强调动作本身；neither + 复数名词表两者都不。~[物件] + was + V-ed + [方式与时间] + by + [双方], and neither + [部门] + really + V-s + it~fWRo~i~x
G09.6~请把两位负责人的联系方式发给客户，但不要把内部的对接群转出去。~Send the two contacts' details to the client, but do not forward the internal coordination group to them.~一件该做、一件不该做，范围不同。~'s 表示复数的各自拥有；否定祈使句省略主语。~Please + V + [复数所有格短语] + to + [接收方], but do not + V + [对象] + to + [对象]~nXEd~r~x
G10.1~我们需要的是一个能说清楚"为什么现在不做"的方案，而不是一份把数据堆得满满的报告。~What we need is a proposal that can explain clearly why we are not doing it now, not a report that simply piles up data.~真正需要的与不需要的是两类不同的东西。~explain 是动词，后接宾语从句；that 引导定语从句修饰名词。~What we need is + [名词] + that can + V + [宾语从句], not + [名词] + that + V-s + [对象]~fWRo~v~x
G10.1~他在会上的表现相当冷静，会后却对同事说了一句非常难听的话。~He was remarkably calm during the meeting, yet afterwards he said something quite unpleasant to a colleague.~前半描述表现，后半描述言行，反差明显。~calm 与 unpleasant 都是描述人的形容词；remarkably 修饰形容词。~[主语] + was + [程度副词] + [形容词] + [时间], yet afterwards + [主语] + said + [形容词修饰的名词]~nSCd~v~x
G10.2~刚刚被财务驳回的那版预算表，我们必须彻底重做，而不是小修小补。~The budget sheet that was just rejected by finance has to be redone from scratch rather than patched up.~修饰语很长，谓语在它之后。~过去分词短语作后置定语；has to 表义务。~The + [名词] + that was just + V-ed by + [方] + has to be + V-ed + [方式] + rather than + V-ed~fWNd~r~t
G10.2~只有在明确了负责人和交付时间之后，这场讨论才可能结束。~This discussion can only end once both the owner and the delivery date have been made clear.~一个必要条件排在结果之前。~can only...once 表唯一路径；make clear 是复合宾语结构。~This + [名词] + can only + V + once + [两件事] + have been + V-ed~fWRo~s~c
G10.3~这个方案在理论上说得通，可落到真实数据里就几乎完全站不住脚了。~The proposal holds together in theory, but applied to the real data it is almost completely untenable.~同一个判断在不同条件下得出相反结论。~hold together 与 hold up 是不同的多词动词；almost completely 表接近极限。~[主语] + holds together + [条件], but + [过去分词短语] + it is + almost completely + [形容词]~fWRo~e~x
G10.3~这不是一次靠加班就能解决的失误，它造成的损失比我们原先估计的大得多。~This is not a mistake that can be solved by working late; the damage it has caused is far greater than we originally estimated.~定语从句限定失误性质，再用比较级说明损失。~can be solved by 中 by 引出手段；far greater than 中需用 much 或 far 修饰。~This is not + [名词] + that can be + V-ed by + [手段]; the + [名词] + it has + V-ed is far + 比较级 + than + [过去估计]~fWRo~e~m
G10.4~与其说新版本比旧版本更快，不如说它在长时间运行下稳定得多。~Rather than saying that the new version is faster than the old one, it is far more stable over long runs.~与其说 A 不如说 B，实际是换了一个比较维度。~双重比较级；far more stable 中的 far 表程度。~Rather than saying that + [主语] + is + 比较级 + than + [对象], it is far more + [形容词] + under + [条件]~cECf~v~m
G10.4~这是我参与过的三个项目里沟通成本最高的一个。~This is the one with the highest communication cost among the three projects I have been involved in.~在一个有限范围内做最高级比较。~最高级前要加 the；范围用 among 限定。~This is the one with the + 最高级 + among + [范围] + [过去完成分句作定语]~fWRo~v~m
G10.5~与其说是这条规则造成了延误，不如说是没有人愿意在最后一步停下来核对。~It is not so much this rule that caused the delay as the fact that nobody was willing to stop and check at the last step.~两个可能原因里否定前者、肯定后者。~not so much...as 两侧结构一致；was willing to 用过去时表已错失的机会。~It is not so much + [A] + that + V-ed + [结果] as + [B] + that + [过去时从句]~fWRo~v~r
G10.5~这次复盘的难度不亚于重建整套数据管道，而后者我们只做过一次。~Reviewing this is no less difficult than rebuilding the whole data pipeline, which we have done only once.~一个比较级加一个数量补充。~no less than 表不低于；which 指代前项重建管道。~[动名词短语] + is no less + 比较级 + than + [名词化动作], which + [主语] + have done + [频率]~fWRo~e~m
G10.6~在会上被反复质疑的那份预算表，最终并没有被真正修改过。~The budget sheet that was repeatedly questioned at the meeting was ultimately never actually revised.~两个分词短语都修饰同一名词，谓语在它们之后。~过去分词作定语表被动；never actually 放在过去分词之前。~The + [名词] + that was + V-ed + [场合] + was ultimately never actually + V-ed~fWRo~i~t
G10.6~负责的同事正在等你确认那两处改动，之后才能继续推进。~The colleague in charge is waiting for you to confirm the two changes before the work can move on.~一个正在进行的等待，连着一个前置动作。~wait for sb to do 用不定式；before 后用情态动词表条件。~[主语] + is + V-ing for + [人] + to + [动作] + before + [主语] + can + V~fWRo~i~t
G11.1~自上周三系统升级之后，已经有超过三百个工单提到了同一个报错。~Since the upgrade last Wednesday, more than three hundred tickets have reported the same error.~一个起点时间引出一个至今仍在增加的结果。~since 后接过去时间点；more than three hundred 配复数名词。~Since + [过去时间点事件], more than + [数量] + have + V-ed + [对象]~fWRo~i~t
G11.1~上午十点之前请把签到表发给我，十点之后我就直接按缺席处理了。~Please send me the attendance sheet before ten in the morning; after ten I will treat anyone who has not signed as absent.~两个时间点分界，界限前后的处理不同。~before 与 after 后接时间名词；treat A as B 中 as 引出身份判断。~Please + V + [对象] + before + [时间点] +; after + [时间点] + I will treat + [对象] + as + [状态]~nWNd~r~t
G11.2~出了地铁站往北走两百米，你会看到一栋外墙全是玻璃的旧写字楼。~Go two hundred metres north once you come out of the subway and you will see an old office building with an all-glass facade.~连续的方向与距离说明最终会看到什么。~once 引导的条件从句用现在时；north 作副词说明方向。~Go + [距离] + [方向] + once + [现在时条件], and you will see + [名词] + with + [外层特征]~nTNo~i~t
G11.2~化验室的样本柜必须放在走廊尽头，否则一旦发生泄漏，通风系统根本来不及把气体排出去。~The sample cabinet in the lab must be kept at the end of the corridor; otherwise, if a leak ever happened, the ventilation system would not be able to draw the gas out in time.~位置要求加上失败情形的后果。~must be kept 用被动；if 从句用过去时表假想。~[设备] + must be + V-ed + [位置] +; otherwise, if + [过去时从句], [主语] + would not be able to + [原形动词] + in time~fWNo~r~c
G11.3~从机场到市区如果遇上堵车，导航会临时把你带上一条看起来更短、其实更慢的路线。~If you run into traffic on the way from the airport into town, the navigation will temporarily take you along a route that looks shorter but is actually slower.~一个出行条件引出一个反直觉的路线选择。~run into 表遇上；that 引导的定语从句内含对比。~If + [主语] + run into + [状况] + [出发到达], [工具] + will + V + [人] + along + [含定语从句的路线]~nTNo~i~x
G11.3~列车一旦临时停在途中，乘客就得原路折返，走错方向就得多花一个小时。~Once a train is stopped unexpectedly en route, passengers have to turn back the way they came, and going the wrong way costs them an extra hour.~途中变化之后有两个方向相反的结果。~turn back the way 表沿原路返回；cost 表带来时间代价。~Once + [被动事件], [主语] + have to + [方向动作], and + [动名词短语] + costs + [人] + [时间代价]~nTNo~i~x
G11.4~线上一旦出问题，团队平均需要四十五分钟才能把影响范围确认清楚。~Once something goes wrong in production, the team needs about forty-five minutes on average to establish the full scope of the impact.~一个触发事件加一个固定的处理时长。~go wrong 表出错；on average 表平均值。~Once + [事件], [主语] + needs + [时长] + on average + to + [名词化动作]~fWRo~i~t
G11.4~项目从批准到交付只预留了十周，其中三分之二要花在合规审批上。~The project allows only ten weeks between approval and delivery, two thirds of which will be spent on compliance approval.~总时长中有一大部分被某个环节占掉。~two thirds of which 从句中用将来被动；前置非限定从句。~[主语] + allows + [时长] + between + [A] and [B], + [比例 + of which] + will be + V-ed on + [事项]~fWRo~i~t
G11.5~为了赶在窗口关闭前完成递交，他们改用脚本把数据拆成八个分片分别上传。~In order to submit before the window closed, they used a script to split the data into eight shards and upload them separately.~目的是赶时间，手段是改用脚本。~use A to do B 表手段；split into 表分成。~In order to + [目的与期限], [主语] + used + [手段] + to + [动作] + [结果]~fWRo~e~p
G11.5~为了不影响线上服务，团队选择先用灰度名单逐批放量，而不是一次性全量切换。~In order not to affect the live service, the team chose to release the change batch by batch to a grey list first rather than switching everything over at once.~目的决定手段，还要说明放弃了哪个做法。~choose to do 表选择；rather than 后接动名词。~In order not to + [影响对象], [主语] + chose to + [手段] + first + rather than + V-ing + [对比做法]~fWRn~e~p
G11.6~这套流程最初是为制造业设计的，拿来跑我们这种高度可变的科研项目并不合适。~This process was originally designed for manufacturing, and it is not suitable for running our highly variable research projects.~说明原始用途，再判断当前不适用。~be designed for 表为某种目的设计；suitable for 后接动名词。~This process was originally + V-ed for + [原用途], and it is not + 形容词 + for + V-ing + [当前对象]~fWRo~e~x
G11.6~与其说客户在意价格，不如说他更在意交付时间能不能说准。~It is not so much the price that the client cares about as whether the delivery date can be relied on.~真实关注点与表面关注点不同。~care about 后接 whether 从句；rely on 表依赖。~It is not so much + [A] + that + [主语] + V-s + as + whether + [主语] + can be + V-ed on~fXCo~v~x
P01~如果方便的话，能否请您在下周三之前把签好的合同扫描件发我一份？~If it is convenient for you, could you send me a scanned copy of the signed contract before next Wednesday?~请求要给出条件和期限两层缓冲。~Could you 之后接动词原形；send sb sth 用双宾语。~If it is convenient for [人], could you + V + [接收者] + [对象] + before + [期限]?~fXEt~r~t
P01~打扰了，我想确认一下这个改动是否已经排进计划；如果不方便回复，我可以下周再问。~Sorry to bother you; I would like to confirm whether this change has already been scheduled, and if it is not convenient to reply, I can ask again next week.~先致歉，再提出请求，并主动留出退路。~whether 从句用陈述语序；if it is not convenient to reply 中用不定式。~Sorry to + [动词]; I would like to + [确认动作] + whether + [现在完成时从句], and if it is not convenient + [不定式], I can + [替代动作]~fWEt~r~t
P07~如果您愿意，我可以先把评审纪要整理成结论清单，明早之前发给您过目。~If you would like, I can turn the review notes into a list of conclusions and send them to you for a look before tomorrow morning.~主动提供帮助，并把方式和时间都说明。~turn A into B 表转化；send sth to sb for a look 表送交查看。~If you would like, I can + V + [对象] + into + [结果] + and + V + it + to you + for a look + before + [时间]~fXRt~o~t
P07~需要我替您回这封邮件，还是您想亲自确认一下？~Would you like me to reply to this email on your behalf, or would you prefer to confirm it yourself?~给出两种安排，让对方选择。~Would you like me to 中不定式指代我的动作；on your behalf 表代替某人。~Would you like me to + [动作] + on your behalf, or would you prefer to + [动作] + yourself?~nSEt~o~o
V01~预算这么一收紧，我们只好把线下培训改成线上，费用也只能压到原来的三分之一。~With the budget squeezed, we had to switch the in-person training online and squeeze the cost down to a third of what it was.~一个外部压力导致两处资源调整。~squeeze down 是压缩的可分短语；a third of what it was 用 what 从句指代原来的数量。~With + [名词短语] + V-ed, [主语] + had to + [调整动作] + and + V + [对象] + down to + [比例]~nECo~i~x
V01~如果排期继续往前压，团队迟早要在质量和交付速度之间做出取舍。~If the schedule keeps being compressed, the team will eventually have to choose between quality and delivery speed.~一个持续动作必然引出一个取舍。~keep being + V-ed 表持续被动；choose between A and B 表二选一。~If + [主语] + keeps being + V-ed, [主语] + will eventually have to + choose between + [A] and [B]~fWRn~f~c
V02~会上财务第一次把预算超支的原因挑明了，语气比前几次都直接。~At the meeting finance finally spelled out the reason for the overspend, in a far more direct tone than before.~一个动作被完成，且语气与以往不同。~spell out 是详细说明的多词动词；far more...than 表程度比较。~[机构] + finally + V-ed out + [对象] + in a far more + 比较级 + than before~fWMd~i~m
V02~排查了一整天之后，团队才把问题定位到批处理作业的时区设置上。~It was only after a full day of troubleshooting that the team pinned the problem down to the time-zone setting on the batch job.~耗时很久才得到一个精确结论。~pin down 是定位的多词动词，强调精确；It was...that 是强调结构。~It was only after + [时长 + of 名词化动名词] + that + [主语] + V-ed + [对象] + down to + [定位结果]~fWRo~e~t
V04~随着监管要求不断收紧，这家公司的合规支出已经比三年前翻了一倍多。~As regulatory requirements keep tightening, the company's compliance spending has more than doubled in three years.~一个背景趋势带来可量化的结果。~keep tightening 中 tighten 是动词原形；more than doubled 表增幅超过一倍。~As + [复数名词] + keep + V, [主语] + 's + [名词] + has more than + V-ed + [倍数与时段]~fWRo~i~r
V04~这次升级带来的稳定性提升是实实在在的，可实施过程中遇到的意外也比预期多得多。~The stability gains brought about by this upgrade are real, but the setbacks encountered during implementation are far more numerous than expected.~一项真实收益与一项超预期的代价同时存在。~bring about 表带来；encountered...during... 现在分词作定语。~The + [名词] + brought about by + [事件] + are + [形容词], but the + [名词] + encountered + [时段] + are far more + 比较级 + than + [预期]~fWRo~e~x
`;

const STYLE = { c: "casual", n: "neutral", f: "formal" };
const SITUATION = {
  E: "daily-life", S: "social-relationships", W: "work-study",
  X: "services-transactions", T: "travel-public-life",
};
const GENRE = {
  C: "conversation-chat", E: "email-message", R: "report-explanation",
  N: "instruction-notice", X: "service-exchange",
};
const TONE = {
  f: "friendly-warm", t: "courteous-tactful", d: "direct-firm",
  n: "cautious-tentative", a: "confident-assertive", p: "apologetic-conciliatory",
  o: "detached-objective",
};
const PURPOSE = {
  d: "describe-narrate", i: "inform-update", e: "explain-justify", q: "ask-clarify",
  r: "request-instruct", s: "suggest-advise", o: "offer-invite-arrange",
  v: "agree-disagree-evaluate", n: "accept-refuse-negotiate", p: "apologise-repair",
  k: "thank-acknowledge", f: "predict-speculate-reflect",
};
const RELATIONSHIP = {
  e: "elaboration-identification", t: "time-duration", p: "purpose",
  c: "condition-exception", x: "contrast-concession", r: "cause-reason",
  s: "result-consequence", m: "comparison-degree", a: "addition-sequence",
  o: "alternative-choice",
};
const CONTEXT = { "work-study": "work", "travel-public-life": "travel" };

export const CHALLENGE_PRACTICE_QUESTIONS = [];

const counts = new Map();
for (const line of AUTHORED.trim().split("\n")) {
  const fields = line.split("~");
  if (fields.length !== 9 || fields.some(field => !field.trim())) throw new Error(`Invalid challenge question: ${line}`);
  const [focus_id, prompt_zh, reference_answer, simple, intermediate, complete, category, purpose, relationship] = fields;
  const focus = focuses.find(item => item.id === focus_id);
  if (!focus) throw new Error(`Unknown language focus: ${focus_id}`);
  if (category.length !== 4) throw new Error(`Invalid categories: ${line}`);
  const [style, situation, genre, tone] = category;
  if (genre === "M") {
    if (SITUATION[situation] !== "work-study") throw new Error(`Meeting genre requires a work situation: ${line}`);
  } else if (!GENRE[genre]) throw new Error(`Invalid genre: ${line}`);
  const metadata = {
    situation: SITUATION[situation], genre: genre === "M" ? "meeting-contribution" : GENRE[genre],
    tone: TONE[tone], purpose: PURPOSE[purpose], meaning_relationship: RELATIONSHIP[relationship],
    register: STYLE[style] === "casual" ? "informal" : STYLE[style],
  };
  if (!STYLE[style] || Object.values(metadata).some(value => !value)) throw new Error(`Invalid categories: ${focus_id}`);
  const version = (counts.get(focus_id) || 0) + 1;
  counts.set(focus_id, version);
  CHALLENGE_PRACTICE_QUESTIONS.push({
    id: `language-${focus_id.toLowerCase()}-c${version + 1}`,
    prompt_zh, reference_answer, difficulty: "challenge",
    style: STYLE[style], context: CONTEXT[metadata.situation] || "everyday",
    focus_id, focus: focus.name, error_type: `${focus_id}: ${focus.name}`,
    variant: "complex", hints: { simple, intermediate, complete }, metadata,
    alternative_note: `Guided construction: ${intermediate} The pattern illustrates this focus; accept other natural translations that preserve meaning, scope, time and tone. Describe any difference in practising the focus without calling equivalent English incorrect.`,
  });
}

if (CHALLENGE_PRACTICE_QUESTIONS.length !== 100) throw new Error("The challenge bank must hold exactly 100 questions.");
if ([...counts.values()].some(count => count !== 2)) throw new Error("Each focus must contribute exactly two challenge questions.");
for (const question of CHALLENGE_PRACTICE_QUESTIONS) {
  if (!/\p{Script=Han}/u.test(question.prompt_zh)) throw new Error(`Prompt must be Chinese: ${question.id}`);
  if (/\p{Script=Han}/u.test(question.reference_answer)) throw new Error(`Reference must be English: ${question.id}`);
  if (new Set(Object.values(question.hints)).size !== 3) throw new Error(`Hints must be distinct: ${question.id}`);
  if (!/(\[[^\]]+\]|（[^）]+）)/.test(question.hints.complete)) throw new Error(`Open pattern must keep placeholders: ${question.id}`);
  if (Object.values(question.hints).some(hint => hint.includes(question.reference_answer))) throw new Error(`Hint leaks the reference: ${question.id}`);
}
if (new Set(CHALLENGE_PRACTICE_QUESTIONS.map(question => question.prompt_zh)).size !== 100) throw new Error("Challenge prompts must be unique.");
if (new Set(CHALLENGE_PRACTICE_QUESTIONS.map(question => question.id)).size !== 100) throw new Error("Challenge ids must be unique.");
